FROM python:3.9
LABEL maintainer="robert.goncalves@tradeupgroup.com"
COPY . /app
WORKDIR /app
RUN apt-get update && apt-get install -y openssh-server
RUN pip3 install --upgrade pip
RUN pip3 install -r ./flask/requirements.txt
RUN chmod 600 ./flask/example.pem
EXPOSE 7000
ENTRYPOINT ["python"]
CMD ["./flask/monitor.py"]